apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: result
  type: {{ .Values.service.result.type }}
  ports:
  - name: "result-service"
    port: {{ .Values.service.result.port }}
    targetPort: {{ .Values.service.result.targetPort }}
    nodePort: {{ .Values.service.result.nodePort }}
