apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: vote
  type: {{ .Values.service.vote.type }}
  ports:
  - name: "vote-service"
    port: {{ .Values.service.vote.port }}
    targetPort: {{ .Values.service.vote.targetPort }}
    nodePort: {{ .Values.service.vote.nodePort }}
